name: Auto IP Test

on:
  workflow_dispatch:    # 允许手动运行
  push:
    branches:
      - test            # 只在 test 分支生效

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test branch
        uses: actions/checkout@v4
        with:
          ref: test

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Run test script
        run: python testsp.py

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: good_ips
          path: good_ips.txt
