name: Auto IP Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: test

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Run Test
        run: python testsp.py

      - name: Upload TXT
        uses: actions/upload-artifact@v4
        with:
          name: good_ips
          path: good_ips.txt

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: good_ips_csv
          path: good_ips.csv
